# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Flutter build

on: [push, pull_request]

jobs:
  lint-test-build:
    name: Run linter,test,build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      # Disabled for now, causing issues
      # - run: flutter test
      - run: flutter build apk
